language: generic

before_install:
  # disable services enabled by default
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop

stages:
  - test
  - name: deploy
    if: branch = master
  - name: deploy-test
    if: head_branch = webserver

jobs:
  include:
    - stage: test
      script: eval "$(gimme 1.11)" && make ci
    - stage: deploy
      script: make docker-push
    - stage: deploy-test
      script: make docker-push-test
