language: android
sudo: required
jdk: oraclejdk8

before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
 directories:
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-28.0.0
    - android-28
    - extra

script:
  - android/gradlew build

before_install:
  # decrypt the encrypted keystore
  - openssl aes-256-cbc -K $encrypted_71c5c0872413_key -iv $encrypted_71c5c0872413_iv -in keystore.jks.enc -out keystore.jks -d

before_deploy:
  # sign the apk
  - cp $TRAVIS_BUILD_DIR/keystore.jks $HOME
  - cd android/app/build/outputs/apk
  - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/keystore.jks -storepass $storepass -keypass $keypass app-release-unsigned.apk release-key
  # verify and zip-align the signed apk
  - jarsigner -verify app-release-unsigned.apk
  - "${ANDROID_HOME}/build-tools/24.0.2/zipalign -v 4 app-release-unsigned.apk smarthomeadapters_android.apk"

deploy:
  provider: releases
  file: smarthomeadapters_android.apk
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: "ZkA1kMFHlSseEPFww9HoiZAzpBjjl772rPInd5iGluIm401Smt8UKQbbjRowmRVkdbCIT4r6OkT65rc6u9sAR9OsQgoewdRLmKHYMDM0sIjHr0P10NFMwjFAsnVGJ05LI5ws4CTdPLphO7ex3WsuUnGAr4vevWoHxn7M8WcAWxEFZSoiES8zfaNZSG2cygeIM+R8RlUW5IlKG0AlJDgcxAlr0QcQ1HLo6NZtKQC6UjJF9HEGAAQ3X7lQd1nT1H23ipw2X85vaQtH9eNf052X4R3rR1sweN2bljybNAKpH0fRwibmjF1BJMLLPIByXqqCLW97gRy47ywj5AfPKQVfaPxmAFGEI/tiUfy0A5br+CR0Uss6sK64IJvnBh2bP+N3lovGfW10nuf08HqLPbyULE4GSx3HindBz0Fj1aQFrj8JBZg5Bzd1STHhhGENkkq4AighyJMO2aWJwwpiOtn7YLNh7u3Og9G+sk29No2h3LH9+Ji+ZtcIxWHYTy9ku2ASR0Kc7/L3MLHI82X4CidlFaNgs3lxNYWuSujH+herq7w6D1RFzHek+HBiSMW3LoZBlEXH+bBQVWpJu5JupDkTQ13rBGRCLrSg6mv2YcWOiaBLxn4LR750sIGXxmo59Jkybr5aCns5czkytU9B8GZq3Dwv9XDUKzWBTqyjHQrvxJo="

env:
  global:
  - secure: rBzM32s6LkYGkDZIL+tC3lmRaXt7ae5nI2+S4OwDg8RvkFychkwloTagzY9ihQH/nAzOVHcr0IsNclHZL5m+Nyv531pTncqjqRmvbVr2fEkZnp5qZPHe80TV0JS/4acf1KStrNMi7xeHhBXito8x392R5KZz132YNoWQ/0++4gVZA8IiAfwoGQ/40pOd/Hp7tl+qqXAgSUyFaiAIvEtkZbwulebSFofHRIvijnG4SkmUpAept33I3RxB8WZQUXWLyW017W+yhXt1wOf1pF8fAvXkM1tk3e9Eb/VdRQwftsSVO5i6uBHfcYlX4rtX8T2ZbdqzT6IEN8eFf022GFugMKvwhD2iIGuvpeA4DLnb5CszQlejKFd57x2/naZ+nGf5tbVmelkw1001nbGpmweF2VpHOpotkNGZNpUPrhDGO0Fe7EObezlwMY32Yf2nmCApSIRMZyLqsuIhebTAsa8w2efGzShGs1EA7a3nKzHHsmet6ROFQtS3wzwqhXLBCUfrId/EDMtCqHIfOskVcf7mGTbXTAEV2VePDN9U881tP/ccNasHQX1W0o33lWBKR7tiJaeDTJ7GOeWsbJJbK0yh8JT8a37BzU4VQcHkVryjyBLKjpbmWoDyoYOhO2U+i9upYFsD2fMGLG8PuJQ7OAAlz1aNuuiUJXvCxtIL0aLeyHg=
  - secure: x/qvWPaUZLSpzVIKEyUhxuLanWWLQDqFPQzwBD4EmBFBEnYRdFyRcr8f5i3ucKi3OXxR03s+FIsH43I+YmHNZ14jq8C53Rc5UC9YKcGUD2sjywQHBIf6ZupETXx5H3sko2OUuamW5l0A3BsR8yP83zwuS+tWIbtCmhnRvIg7s/N03rbq2Qyulu35hcExzAzEazls7wlfqFKITFqQwmowj/9KVLxp5FdDOAoYZc/omJITH0eVkIMa1DGy04xfMu1Yl18bah5Bx7ce2Uj5Ws9yV4nRkakbtiAxmQ5/v9TSPGmfa1ak1V+v1dZZWjbZVlv0XCGg0I3olSzMbZ0yBiYwP3nsl7VsSN59KY0zw9wbk72TmAReuoVeCTAOHDMbOI9vRKjhSu51qaofuqWrdKhwh6eh8RanDheHZEUF5fGIz+PMfhbHRUlBQ3rksARuwcXeE8A6E56B37raZqKBUn3YpP9cLveDCKe6aKvCrvvqh4gyad5eA9w1BRM4dGVVUvCjIm9DsuOFAkyv2/JWebUIDCZxT950q6ODK+q8fbCLoXsX5RvNhxUslyldqINgJsKKz8YGeasiqrEVAKyndrbFlT2M2PwsD1uEcWk3OR7QVHP2tyJZQCCxhYw5LL3WoG0BsJfR8oBji3nHSO5oxUIOyHtMEaLfuI4Fa3STUhtnSzM=
