language: minimal

jobs:
  include:
    # Compiling reports
    # - stage: test
    #   script:
    #   - docker pull dxjoke/tectonic-docker
    #   - |
    #     for DIR in reports/*/; do
    #       echo "Compiling ${DIR}";
    #       docker run --mount src=${TRAVIS_BUILD_DIR}/${DIR},target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c "tectonic document.tex"
    #     done
    # test
    - stage: test
      script: eval "$(gimme 1.11)" && make ci