language: generic

jobs:
  include:
    # test client server
    - stage: test
      script: eval "$(gimme 1.11)" && cd ${TRAVIS_BUILD_DIR}/clientserver && make test
    # test user server
    - stage: test
      script: eval "$(gimme 1.11)" && cd ${TRAVIS_BUILD_DIR}/userserver && make test
    # test robot server
    - stage: test
      script: eval "$(gimme 1.11)" && cd ${TRAVIS_BUILD_DIR}/robotserver && make test
