language: generic

before_install:
  # disable services enabled by default
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop

jobs:
  include:
    # test info server
    - stage: test
      script: eval "$(gimme 1.11)" && cd ${TRAVIS_BUILD_DIR}/infoserver && make test
