language: generic

before_install:
  # disable services enabled by default
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop

jobs:
  include:
    # test client server
    - stage: test
      script: eval "$(gimme 1.11)" && cd ${TRAVIS_BUILD_DIR}/clientserver && make test
    # test switch server
    - stage: test
      script: eval "$(gimme 1.11)" && cd ${TRAVIS_BUILD_DIR}/switchserver && make test
    # test robot server
    - stage: test
      script: eval "$(gimme 1.11)" && cd ${TRAVIS_BUILD_DIR}/robotserver && make test