language: generic

script:
  # test webserver (with go 1.11)
  - eval "$(gimme 1.11)" && cd clientserver && go get -v ./... && go test
  - eval "$(gimme 1.11)" && cd userserver && go get -v ./... && go test
