language: generic

before_install:
  # disable services enabled by default
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  # login so we can push to dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

stages:
  - test
  - name: deploy
    if: branch = master AND type != pull_request
  - name: deploy-test
    if: head_branch = webserver

jobs:
  include:
    - stage: test
      script: eval "$(gimme 1.11)" && make ci
    - stage: deploy
      script: make docker-push
    - stage: deploy-test
      script: make docker-push-test
