language: generic

jobs:
  include:
    # test client server
    - stage: test
      script: eval "$(gimme 1.11)" && cd clientserver && go get -v ./... && go test
    # test user server
    - stage: test
      script: eval "$(gimme 1.11)" && cd userserver && go get -v ./... && go test