version: '3'

services:
  # database managment
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    build: 
      context: ./database
    restart: always
    environment:
      - POSTGRES_PASSWORD
  userserver:
    build: 
      context: ./userserver
    restart: always