version: '3'

services:
  switchdb:
    build: 
      context: ./switchserver/database
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - switch_database_data:/var/lib/postgresql/data
  switchserver:
    build: 
      context: ./switchserver
    depends_on:
      - switchdb
    restart: always
    ports:
      - 8081:80
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_DATABASE=postgres
      - DB_URL=switchdb
  clientserver:
    build: 
      context: ./clientserver
    restart: always
    ports:
      - 80:80
volumes:
  switch_database_data: