version: 2

workflows:
  version: 2
  main:
    jobs:
      - test-services
      - lint-services:
          requires:
            - test-services
      - build-reports
      - test-android
      - lint-android:
          requires:
            - test-android

jobs:
  test-services:
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run:
          name: Test account-app
          command: go test
          working_directory: services/account-app
      - run:
          name: Test clientserver
          command: go test
          working_directory: services/clientserver
      - run:
          name: Test infoserver
          command: go test
          working_directory: services/infoserver
      - run:
          name: Test robotserver
          command: go test
          working_directory: services/robotserver
      - run:
          name: Test switchserver
          command: go test
          working_directory: services/switchserver
      - run:
          name: Test termostatserver
          command: go test
          working_directory: services/termostatserver
      - run:
          name: Test userserver
          command: go test
          working_directory: services/userserver

  lint-services:
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run: 
          name: Install golangci-lint
          command: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s v1.15.0
      - run:
          name: Lint account-app
          command: golangci-lint run
          working_directory: services/account-app
      - run:
          name: Lint clientserver
          command: golangci-lint run
          working_directory: services/clientserver
      - run:
          name: Lint infoserver
          command: golangci-lint run
          working_directory: services/infoserver
      - run:
          name: Lint robotserver
          command: golangci-lint run
          working_directory: services/robotserver
      - run:
          name: Lint switchserver
          command: golangci-lint run
          working_directory: services/switchserver
      - run:
          name: Lint termostatserver
          command: golangci-lint run
          working_directory: services/termostatserver
      - run:
          name: Lint userserver
          command: golangci-lint run
          working_directory: services/userserver
  
          build-android:

  build-reports:
    docker:
      - image: paperist/alpine-texlive-ja
    steps:
      - checkout
      - run:
          name: Compile demo 1 report
          working_directory: reports/demo-1
          command: |
            latexmk document.tex
      - run:
          name: Compile demo 2 report
          working_directory: reports/demo-2
          command: |
            latexmk document.tex
      - run:
          name: Compile demo 3 report
          working_directory: reports/demo-3
          command: |
            latexmk document.tex
      - run:
          name: Compile project-plan report
          working_directory: reports/project-plan
          command: |
            latexmk document.tex
      - run:
          name: Compile technical-report report
          working_directory: reports/technical-report
          command: |
            latexmk document.tex
      - run:
          name: Compile user-guide report
          working_directory: reports/user-guide
          command: |
            latexmk document.tex

  test-android:
    docker:
      - image: circleci/android:api-25-alpha
    steps:
      - checkout
      - run:
          name: Run Tests
          command: ./gradlew test
  
  lint-android:
    docker:
      - image: circleci/android:api-25-alpha
    steps:
      - checkout
      - run:
          name: Run Lint
          command: ./gradlew lint