openapi: 3.0.2
info:
  description: "This is the API for smart home adapter clients."
  version: "0.1.0"
  title: "Smart Home Adapters"
  licence:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
